version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_db
    ports:
      - "3306:3306"
    networks:
      - backend

  movie-service:
    build: ./movie-service
    container_name: movie-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - backend

  show-service:
    build: ./show-service
    container_name: show-service
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - backend

  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    depends_on:
      - mysql
    ports:
      - "8083:8083"
    networks:
      - backend

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mysql
    ports:
      - "8084:8084"
    networks:
      - backend

networks:
  backend:
    driver: bridge
