version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_db
    ports:
      - "3306:3306"
    networks:
      - backend

  movie-service:
    build: ./movie-service
    container_name: movie-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - backend

  show-service:
    build: ./show-service
    container_name: show-service
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge
